import randRange from "../utils/randRange";

const COINS = [
  {
    id: "bitcoin",
    path: "bitcoin",
    code: "BTC",
    close: randRange(0, 1),
    uad_percent: randRange(0, 500) / 100,
  },
  {
    id: "ethereum",
    path: "ethereum",
    code: "ETH",
    close: randRange(0, 1),
    uad_percent: randRange(0, 500) / 100,
  },
  {
    id: "litecoin",
    path: "litecoin",
    code: "LTC",
    close: randRange(0, 1),
    uad_percent: randRange(0, 500) / 100,
  },
  {
    id: "iota",
    path: "iota",
    code: "IOTA",
    close: randRange(0, 1),
    uad_percent: randRange(0, 500) / 100,
  },
  {
    id: "solana",
    path: "solana",
    code: "SOL",
    close: randRange(0, 1),
    uad_percent: randRange(0, 500) / 100,
  },
  {
    id: "polkadot",
    path: "polkadot",
    code: "DOT",
    close: randRange(0, 1),
    uad_percent: randRange(0, 500) / 100,
  },
  {
    id: "xrp",
    path: "xrp",
    code: "XRP",
    close: randRange(0, 1),
    uad_percent: randRange(0, 500) / 100,
  },
  {
    id: "cardano",
    path: "cardano",
    code: "ADA",
    close: randRange(0, 1),
    uad_percent: randRange(0, 500) / 100,
  },
  {
    id: "dogecoin",
    path: "dogecoin",
    code: "DOGE",
    close: randRange(0, 1),
    uad_percent: randRange(0, 500) / 100,
  },
  {
    id: "stellar",
    path: "stellar",
    code: "XLM",
    close: randRange(0, 1),
    uad_percent: randRange(0, 500) / 100,
  },
  {
    id: "uniswap",
    path: "uniswap",
    code: "UNI",
    close: randRange(0, 1),
    uad_percent: randRange(0, 500) / 100,
  },
  {
    id: "avalanche",
    path: "avalanche",
    code: "AVAX",
    close: randRange(0, 1),
    uad_percent: randRange(0, 500) / 100,
  },
  {
    id: "shiba-inu",
    path: "shibainu",
    code: "SHIB",
    close: randRange(0, 1),
    uad_percent: randRange(0, 500) / 100,
  },
  {
    id: "filecoin",
    path: "filecoin",
    code: "FIL",
    close: randRange(0, 1),
    uad_percent: randRange(0, 500) / 100,
  },
  {
    id: "internet-computer",
    path: "internetComputer",
    code: "ICP",
    close: randRange(0, 1),
    uad_percent: randRange(0, 500) / 100,
  },
  {
    id: "cronos",
    path: "cronos",
    code: "CRO",
    close: randRange(0, 1),
    uad_percent: randRange(0, 500) / 100,
  },
];

export default COINS;
